on:
  push:
    branches:
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: nixbuild/nix-quick-install-action@v21
      - uses: actions/checkout@v3
      - run: nix develop -c './build.sh'
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_DEPLOY_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "f1bet"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
